#!/usr/bin/env python3
"""Translate kanji meanings from English to Bulgarian."""

import json
import re

# Load extended translations from a separate approach
# We'll use a comprehensive dictionary loaded from inline data

def get_translations():
    """Get English to Bulgarian translations."""
    # Base translations dictionary
    t = {}
    
    # Add core vocabulary
    core = """
one=едно
two=две
three=три
four=четири
five=пет
six=шест
seven=седем
eight=осем
nine=девет
ten=десет
hundred=сто
thousand=хиляда
day=ден
sun=слънце
month=месец
moon=луна
year=година
time=време
hour=час
minute=минута
second=секунда
morning=сутрин
evening=вечер
night=нощ
today=днес
tomorrow=утре
yesterday=вчера
week=седмица
now=сега
before=преди
after=след
early=рано
late=късно
spring=пролет
summer=лято
autumn=есен
winter=зима
period=период
generation=поколение
age=възраст
era=епоха
moment=момент
water=вода
fire=огън
tree=дърво
wood=дърво
mountain=планина
river=река
sea=море
ocean=океан
lake=езеро
stone=камък
rock=скала
earth=земя
ground=земя
soil=почва
wind=вятър
rain=дъжд
snow=сняг
cloud=облак
sky=небе
heaven=небе
star=звезда
flower=цвете
grass=трева
leaf=лист
root=корен
branch=клон
gold=злато
silver=сребро
iron=желязо
metal=метал
copper=мед
steel=стомана
jewel=бижу
gem=скъпоценен камък
diamond=диамант
pearl=перла
fog=мъгла
mist=мъгла
ice=лед
sand=пясък
dust=прах
mud=кал
clay=глин
crystal=кристал
flame=пламък
smoke=дим
shadow=сянка
shade=сянка
stream=поток
wave=вълна
tide=прилив
island=остров
coast=крайбрежие
shore=бряг
beach=плаж
valley=долина
hill=хълм
peak=връх
summit=връх
cave=пещера
forest=гора
jungle=джунгла
desert=пустиня
field=поле
meadow=поляна
garden=градина
orchard=овощна градина
vineyard=лозе
fountain=фонтан
well=кладенец
pond=езерце
pool=басейн
swamp=блато
marsh=блато
east=изток
west=запад
south=юг
north=север
up=нагоре
above=горе
over=над
top=връх
down=надолу
below=долу
under=под
bottom=дъно
left=ляво
right=дясно
center=център
middle=среда
inside=вътре
outside=вън
front=пред
back=зад
behind=зад
between=между
among=сред
side=страна
direction=посока
place=място
near=близо
far=далеч
upper=горен
lower=долен
inner=вътрешен
outer=външен
surface=повърхност
interior=интериор
exterior=екстериор
location=местоположение
position=позиция
situation=ситуация
environment=среда
person=човек
people=хора
man=мъж
woman=жена
child=дете
boy=момче
girl=момиче
baby=бебе
father=баща
mother=майка
parent=родител
brother=брат
sister=сестра
family=семейство
home=дом
house=къща
friend=приятел
enemy=враг
king=цар
queen=кралица
prince=принц
princess=принцеса
lord=господар
master=господар
servant=слуга
head=глава
face=лице
eye=око
ear=ухо
nose=нос
mouth=уста
hand=ръка
foot=крак
leg=крак
arm=ръка
heart=сърце
body=тяло
mind=ум
spirit=дух
soul=душа
life=живот
death=смърт
birth=раждане
self=аз
oneself=себе си
hair=коса
skin=кожа
bone=кост
muscle=мускул
blood=кръв
flesh=плът
finger=пръст
toe=пръст на крака
thumb=палец
nail=нокът
palm=длан
wrist=китка
elbow=лакът
shoulder=рамо
knee=коляно
ankle=глезен
neck=врат
throat=гърло
chest=гръден кош
stomach=стомах
back=гръб
waist=кръст
hip=хълбок
tail=опашка
wing=крило
feather=перо
horn=рог
tooth=зъб
tongue=език
lip=устна
beard=брада
tear=сълза
sweat=пот
breath=дъх
voice=глас
smile=усмивка
sound=звук
noise=шум
silence=тишина
go=отивам
come=идвам
return=връщам се
enter=влизам
exit=излизам
leave=напускам
arrive=пристигам
see=виждам
look=гледам
watch=наблюдавам
read=чета
hear=чувам
listen=слушам
say=казвам
speak=говоря
talk=говоря
tell=разказвам
ask=питам
answer=отговарям
write=пиша
draw=рисувам
make=правя
do=правя
create=създавам
build=строя
cut=режа
break=чупя
give=давам
receive=получавам
get=вземам
take=вземам
hold=държа
carry=нося
bring=нося
send=изпращам
buy=купувам
sell=продавам
pay=плащам
use=използвам
work=работя
study=уча
learn=уча
teach=преподавам
know=знам
think=мисля
understand=разбирам
remember=помня
forget=забравям
like=харесвам
love=обичам
hate=мразя
want=искам
need=нуждая се
hope=надявам се
wish=пожелавам
try=опитвам
begin=започвам
start=започвам
end=завършвам
finish=завършвам
stop=спирам
continue=продължавам
wait=чакам
meet=срещам
help=помагам
save=спасявам
protect=пазя
attack=нападам
fight=боря се
win=печеля
lose=губя
play=играя
run=бягам
walk=ходя
swim=плувам
fly=летя
jump=скачам
sit=седя
stand=стоя
sleep=спя
wake=събуждам се
eat=ям
drink=пия
cook=готвя
grow=раста
die=умирам
live=живея
open=отварям
close=затварям
turn=завъртам
move=движа
change=променям
become=ставам
put=слагам
place=поставям
pull=дърпам
push=бутам
raise=вдигам
lower=свалям
join=присъединявам
connect=свързвам
separate=отделям
divide=разделям
add=добавям
increase=увеличавам
decrease=намалявам
reduce=намалявам
accept=приемам
refuse=отказвам
reject=отхвърлям
allow=позволявам
permit=позволявам
forbid=забранявам
obey=подчинявам се
follow=следвам
lead=водя
call=викам
name=назовавам
choose=избирам
select=избирам
find=намирам
search=търся
catch=хващам
touch=докосвам
hit=удрям
kill=убивам
wash=мия
clean=чистя
show=показвам
hide=крия
cover=покривам
fill=пълня
empty=празня
pass=предавам
cross=пресичам
climb=катеря се
fall=падам
rise=изгрявам
set=залязвам
shine=блестя
gather=събирам
collect=събирам
measure=меря
count=броя
compare=сравнявам
judge=съдя
decide=решавам
solve=решавам
fix=поправям
repair=поправям
correct=поправям
improve=подобряям
develop=развивам
produce=произвеждам
perform=изпълнявам
practice=практикувам
exercise=упражнявам
train=тренирам
prepare=подготвям
organize=организирам
arrange=подреждам
adjust=нагласям
adapt=адаптирам
apply=прилагам
attach=прикачвам
bind=връзвам
tie=връзвам
wrap=увивам
pack=опаковам
load=товаря
lift=вдигам
throw=хвърлям
cast=хвърлям
shoot=стрелям
aim=целя се
point=соча
direct=насочвам
guide=напътствам
drive=карам
ride=яхам
row=гребя
sail=плавам
flow=тека
float=плувам
sink=потъвам
melt=топя се
freeze=замразявам
burn=горя
boil=кипна
mix=смесвам
stir=разбърквам
shake=разтърсвам
bend=огъвам
stretch=разтеглям
twist=усуквам
squeeze=стискам
press=натискам
rub=търкам
scratch=драскам
dig=копая
bury=погребвам
plant=засаждам
sow=сея
harvest=жъна
pick=бера
pluck=скубя
hunt=ловувам
chase=преследвам
pursue=преследвам
escape=бягам
flee=бягам
avoid=избягвам
prevent=предотвратявам
defend=защитавам
guard=пазя
rescue=спасявам
aid=помагам
assist=помагам
support=подкрепям
encourage=насърчавам
comfort=успокоявам
calm=успокоявам
please=радвам
satisfy=удовлетворявам
disappoint=разочаровам
surprise=изненадвам
shock=шокирам
frighten=плаша
scare=плаша
terrify=ужасявам
worry=тревожа
concern=тревожа
interest=интересувам
attract=привличам
charm=очаровам
fascinate=увличам
amaze=изумявам
astonish=изумявам
wonder=чудя се
doubt=съмнявам се
suspect=подозирам
fear=страхувам се
trust=доверявам се
believe=вярвам
pray=моля се
thank=благодаря
apologize=извинявам се
excuse=извинявам
blame=обвинявам
criticize=критикувам
complain=оплаквам се
explain=обяснявам
describe=описвам
express=изразявам
represent=представлявам
symbolize=символизирам
mean=знача
signify=означавам
imply=подразбирам
suggest=предлагам
recommend=препоръчвам
advise=съветвам
warn=предупреждавам
threaten=заплашвам
order=заповядвам
command=командвам
demand=изисквам
request=моля
invite=каня
welcome=приветствам
greet=поздравявам
introduce=представям
marry=оженвам
divorce=развеждам
bear=раждам
feed=храня
educate=образовам
inform=информирам
notify=уведомявам
publish=публикувам
broadcast=излъчвам
record=записвам
copy=копирам
print=печатам
mark=маркирам
sign=подписвам
seal=печатвам
stamp=печатвам
own=притежавам
possess=притежавам
have=имам
lack=липсва
owe=дължа
belong=принадлежа
consist=състоя се
contain=съдържам
include=включвам
exclude=изключвам
involve=включвам
matter=имам значение
exist=съществувам
appear=появявам се
disappear=изчезвам
vanish=изчезвам
fade=избледнявам
occur=случвам се
happen=случвам се
result=резултирам
succeed=успявам
fail=провалям се
manage=управлявам
handle=обработвам
treat=третирам
deal=разправям
face=изправям се
suffer=страдам
endure=търпя
tolerate=търпя
resist=съпротивлявам се
oppose=противопоставям се
struggle=боря се
compete=състезавам се
conquer=побеждавам
defeat=побеждавам
destroy=разрушавам
damage=повреждам
harm=вредя
hurt=наранявам
injure=наранявам
wound=раня
ruin=разрушавам
spoil=развалям
waste=пилея
miss=пропускам
neglect=пренебрегвам
ignore=игнорирам
overlook=пренебрегвам
abandon=изоставям
desert=изоставям
remain=оставам
stay=оставам
keep=пазя
maintain=поддържам
preserve=съхранявам
conserve=пазя
reserve=запазвам
store=съхранявам
accumulate=натрупвам
pile=натрупвам
heap=натрупвам
stack=натрупвам
assemble=събирам
convene=събирам
summon=извиквам
withdraw=оттеглям
retire=пенсионирам се
recede=отдръпвам се
decline=намалявам
subside=стихвам
abate=намалявам
ease=облекчавам
relieve=облекчавам
alleviate=облекчавам
soothe=успокоявам
console=успокоявам
cheer=надъхвам
hearten=надъхвам
inspire=вдъхновявам
motivate=мотивирам
stimulate=стимулирам
excite=вълнувам
arouse=възбуждам
awaken=събуждам
rouse=събуждам
stir=разбърквам
disturb=безпокоя
upset=разстроен
confuse=обърквам
bewilder=обърквам
perplex=обърквам
puzzle=обърквам
alarm=тревожа
dismay=разочаровам
discourage=обезсърчавам
depress=депресирам
oppress=угнетявам
suppress=потискам
repress=потискам
grieve=скърбя
mourn=оплаквам
lament=оплаквам
regret=съжалявам
repent=разкайвам се
sympathize=съчувствам
empathize=съпреживявам
compassionate=съчувствам
pity=съжалявам
    """
    
    for line in core.strip().split('\n'):
        if '=' in line:
            en, bg = line.split('=', 1)
            t[en.strip()] = bg.strip()
    
    # Add adjectives
    adj = """
big=голям
large=голям
huge=огромen
great=велик
small=малък
little=малък
tiny=малък
short=къс
tall=висок
high=висок
low=нисък
long=дълъг
wide=широк
narrow=тесен
thick=дебел
thin=тънък
fat=дебел
slim=слаб
heavy=тежък
light=лек
strong=силен
weak=слаб
hard=твърд
soft=мек
smooth=гладък
rough=груб
sharp=остър
dull=тъп
bright=ярък
dark=тъмен
clear=ясен
cold=студен
cool=хладен
hot=горещ
warm=топъл
dry=сух
wet=мокър
fresh=пресен
new=нов
old=стар
young=млад
ancient=древен
modern=модерен
early=ранен
quick=бърз
fast=бърз
slow=бавен
easy=лесен
difficult=труден
simple=прост
complex=сложен
beautiful=красив
pretty=хубав
handsome=красив
ugly=грозен
good=добър
bad=лош
evil=зъл
kind=добър
nice=приятен
fine=фин
poor=беден
rich=богат
expensive=скъп
cheap=евтин
free=свободен
busy=зает
healthy=здрав
sick=болен
happy=щастлив
glad=радостен
joyful=весел
cheerful=весел
sad=тъжен
angry=ядосан
calm=спокоен
quiet=тих
famous=известен
unknown=неизвестен
common=често срещан
rare=рядък
normal=нормален
special=специален
whole=цял
complete=пълен
full=пълен
empty=празен
true=вярно
real=реален
false=фалшив
wrong=грешен
correct=правилен
safe=безопасен
dangerous=опасен
possible=възможен
impossible=невъзможен
certain=сигурен
public=публичен
private=личен
open=отворен
closed=затворен
ready=готов
important=важен
serious=сериозен
funny=смешен
interesting=интересен
boring=скучен
mysterious=мистериозен
strange=странен
particular=конкретен
specific=специфичен
general=общ
various=различен
different=различен
same=същ
similar=подобен
equal=равен
right=десен
upper=горен
lower=долен
inner=вътрешен
outer=външен
deep=дълбок
shallow=плитък
broad=широк
sweet=сладък
bitter=горчив
salty=солен
sour=кисел
spicy=пикантен
plain=прост
fancy=изискан
gentle=нежен
tender=нежен
harsh=строг
strict=строг
mild=мек
wild=див
tame=кротък
fierce=яростен
cruel=жесток
brutal=брутален
violent=насилствен
aggressive=агресивен
peaceful=мирен
graceful=изящен
elegant=елегантен
awkward=непохватен
clumsy=непохватен
skillful=напреднал
clever=умен
wise=мъдър
foolish=глупав
stupid=тъп
silly=глупав
intelligent=интелигентен
smart=умен
brilliant=брилянтен
excellent=отличен
perfect=перфектен
wonderful=чудесен
terrible=страшен
awful=ужасен
horrible=ужасен
amazing=удивителен
surprising=изненадващ
shocking=шокиращ
exciting=вълнуващ
tiring=изморителен
relaxing=отпускащ
comfortable=удобен
uncomfortable=неудобен
convenient=удобен
inconvenient=неудобен
available=наличен
unavailable=недостъпен
sufficient=достатъчен
enough=достатъчно
abundant=изобилен
scarce=оскъден
precious=ценен
valuable=ценен
worthless=безполезен
useful=полезен
useless=безполезен
effective=ефективен
efficient=ефикасен
powerful=мощен
mighty=могъщ
vulnerable=уязвим
resistant=резистентен
flexible=гъвкав
rigid=твърд
elastic=еластичен
solid=твърд
liquid=течен
stable=стабилен
unstable=нестабилен
steady=устойчив
firm=твърд
loose=свободен
tight=стегнат
dense=плътен
pure=чист
impure=нечист
clean=чист
dirty=мръсен
neat=подреден
messy=разхвърлян
tidy=подреден
organized=организиран
systematic=систематичен
logical=логичен
rational=рационален
reasonable=разумен
conscious=съзнателен
aware=наясно
asleep=заспал
awake=буден
alert=бдителен
attentive=внимателен
careful=внимателен
cautious=предпазлив
careless=небрежен
reckless=безразсъден
bold=смел
brave=храбър
courageous=смел
fearless=безстрашен
heroic=героичен
cowardly=страхлив
timid=плах
shy=срамежлив
modest=скромен
humble=смирен
proud=горд
arrogant=надут
vain=суета
selfish=егоистичен
generous=щедър
greedy=алчен
ambitious=амбициозен
lazy=мързелив
diligent=трудолюбив
hardworking=работлив
patient=търпелив
impatient=нетърпелив
persistent=упорит
consistent=последователен
reliable=надежден
trustworthy=надежден
honest=честен
dishonest=нечестен
sincere=искрен
faithful=верен
loyal=верен
devoted=предан
committed=ангажиран
responsible=отговорен
irresponsible=безотговорен
dependent=зависим
independent=независим
bound=обвързан
restricted=ограничен
limited=ограничен
unlimited=неограничен
absolute=абсолютен
relative=относителен
comparative=сравнителен
superior=превъзхождащ
inferior=подчинен
senior=старши
junior=младши
major=основен
minor=незначителен
primary=първичен
secondary=вторичен
main=главен
chief=главен
principal=основен
central=централен
basic=основен
fundamental=фундаментален
essential=съществен
vital=жизнен
critical=критичен
crucial=решаващ
urgent=спешен
pressing=належащ
immediate=незабавен
sudden=внезапен
gradual=постепенен
rapid=бърз
swift=бърз
prompt=незабавен
instant=моментален
temporary=временен
permanent=постоянен
eternal=вечен
immortal=безсмъртен
mortal=смъртен
deadly=смъртоносен
fatal=фатален
lethal=смъртоносен
harmful=вреден
harmless=безвреден
beneficial=полезен
advantageous=благоприятен
favorable=благоприятен
unfavorable=неблагоприятен
profitable=печеливш
worthwhile=стоящ си
fruitful=плодотворен
successful=успешен
unsuccessful=неуспешен
triumphant=триумфиращ
victorious=победоносен
financial=финансов
economic=икономически
political=политически
social=социален
cultural=културен
educational=образователен
academic=академичен
scientific=научен
technical=технически
practical=практически
theoretical=теоретичен
professional=професионален
official=официален
unofficial=неофициален
formal=формален
informal=неформален
legal=законен
illegal=незаконен
criminal=престъпен
civil=граждански
military=военен
religious=религиозен
sacred=свещен
holy=свят
divine=божествен
secular=светски
royal=кралски
noble=благороден
civilian=цивилен
urban=градски
rural=селски
industrial=индустриален
agricultural=земеделски
commercial=търговски
residential=жилищен
medical=медицински
physical=физически
mental=психически
spiritual=духовен
material=материален
immaterial=нематериален
domestic=домашен
foreign=чужд
native=роден
natural=естествен
artificial=изкуствен
synthetic=синтетичен
organic=органичен
inorganic=неорганичен
chemical=химически
biological=биологичен
geographical=географски
historical=исторически
contemporary=съвременен
recent=скорошен
latest=последен
current=текущ
present=настоящ
past=минал
future=бъдещ
forthcoming=предстоящ
upcoming=предстоящ
imminent=неизбежен
inevitable=неизбежен
unavoidable=неизбежен
probable=вероятен
likely=вероятно
unlikely=невероятно
improbable=невероятен
doubtful=съмнителен
questionable=съмнителен
undeniable=неоспорим
indisputable=неоспорим
obvious=очевиден
evident=очевиден
apparent=видим
plain=ясно
distinct=различен
explicit=явен
implicit=скрит
hidden=скрит
secret=тайна
concealed=скрит
revealed=разкрит
disclosed=разкрит
exposed=изложен
uncovered=разкрит
covered=покрит
bare=гол
naked=гол
protected=защитен
defended=защитен
guarded=пазен
shielded=защитен
sheltered=приютен
immune=имунизиран
tolerant=търпелив
intolerant=нетърпелив
sensitive=чувствителен
insensitive=нечувствителен
emotional=емоционален
intellectual=интелектуален
creative=творчески
innovative=иновативен
original=оригинален
elegant=елегантен
attractive=привлекателен
charming=очарователен
fascinating=увлекателен
absorbing=увличащ
engaging=ангажиращ
captivating=пленителен
enchanting=очарователен
enthralling=увличащ
riveting=увличащ
compelling=убедителен
convincing=убедителен
persuasive=убедителен
eloquent=красноречив
articulate=артикулиран
expressive=изразителен
vivid=жив
lively=жив
animated=оживен
spirited=вдъхновен
enthusiastic=ентусиазиран
passionate=страстен
zealous=ревностен
fervent=пламенен
ardent=горещ
eager=нетърпелив
keen=остър
anxious=тревожен
restless=безпокоен
agitated=развълнуван
excited=развълнуван
thrilled=развълнуван
exhilarated=възбуден
elated=възвишен
ecstatic=екстатичен
euphoric=евфоричен
blissful=блажен
blessed=благословен
heavenly=небесен
celestial=небесен
cosmic=космически
universal=универсален
boundless=безграничен
limitless=безграничен
vast=обширен
immense=огромен
enormous=огромен
tremendous=огромен
gigantic=гигантски
colossal=колосален
massive=масивен
substantial=значителен
considerable=значителен
sizable=голям
ample=достатъчен
abundant=изобилен
plentiful=изобилен
copious=обилен
profuse=обилен
lavish=щедър
luxuriant=разкошен
affluent=заможен
opulent=богат
sumptuous=разкошен
splendid=великолепен
magnificent=великолепен
grand=велик
majestic=величествен
impressive=впечатляващ
striking=поразителен
stunning=зашеметяващ
astonishing=изумителен
astounding=удивителен
breathtaking=спиращ дъха
spectacular=спектакуларен
picturesque=живописен
scenic=живописен
appealing=привлекателен
inviting=поканителен
tempting=изкусителен
enticing=съблазнителен
alluring=примамлив
seductive=съблазнителен
provocative=провокативен
challenging=предизвикателен
stimulating=стимулиращ
inspiring=вдъхновяващ
heartening=ободряващ
uplifting=вдъхновяващ
exhilarating=развълнуващ
thrilling=вълнуващ
electrifying=електризиращ
stirring=вълнуващ
moving=трогателен
touching=трогателен
poignant=силен
pathetic=патетичен
pitiful=жалък
lamentable=жалък
deplorable=плачевен
unfortunate=нещастен
unlucky=нещастен
miserable=нещастен
wretched=окаян
woeful=тъжен
sorrowful=тъжен
melancholy=меланхоличен
somber=мрачен
gloomy=мрачен
dismal=мрачен
dreary=скучен
bleak=безрадостен
grim=мрачен
austere=строг
spartan=спартански
stark=строг
exposed=изложен
defenseless=беззащитен
unprotected=незащитен
disposed=разположен
inclined=склонен
apt=подходящ
bound=свързан
destined=предназначен
doomed=обречен
fated=съден
accursed=проклет
damned=проклет
cursed=проклет
fortunate=късметлия
lucky=късметлия
advantaged=привилегирован
privileged=привилегирован
favored=благоприятстван
preferred=предпочитан
darling=любим
beloved=обичан
loved=обичан
adored=обожаван
cherished=ценен
treasured=скъпоценен
prized=ценен
valued=ценен
esteemed=уважаван
respected=уважаван
honored=почетен
revered=почитан
venerated=почитан
worshiped=обожаван
idolized=идолизиран
idealized=идеализиран
glorified=прославен
exaggerated=преувеличен
inflated=надуен
swollen=подут
bloated=подут
expanded=разширен
extended=разширен
stretched=разтегнат
widened=разширен
broadened=разширен
enlarged=разширен
amplified=усилен
magnified=увеличен
intensified=интензифициран
heightened=повишен
raised=повишен
elevated=повишен
lifted=повдигнат
upgraded=обновен
promoted=повишен
advanced=напреднал
improved=подобрен
enhanced=подобрен
augmented=увеличен
boosted=повишен
increased=увеличен
grown=нараснал
developed=развит
evolved=еволюирал
progressed=прогресирал
matured=узрял
ripened=узрял
aged=остарял
seasoned=сезониран
cured=излекуван
preserved=съхранен
pickled=маринован
fermented=ферментирал
rotten=гнил
decayed=разложен
decomposed=разложен
putrid=гнил
rancid=вкиснат
stale=застоял
foul=мръсен
filthy=мръсен
dirty=мръсен
soiled=цапнат
stained=петнист
spotted=петнист
marked=маркиран
scarred=белезникав
blemished=петнист
flawed=с дефект
defective=дефектен
faulty=неизправен
imperfect=несъвършен
damaged=повреден
impaired=увреден
injured=наранен
hurt=наранен
wounded=ранен
bruised=натъртен
battered=бит
beaten=пребит
abused=злоупотребен
misused=злоупотребен
worn=износен
weathered=изветрян
antique=античен
vintage=винтидж
old-fashioned=старомоден
outdated=остарял
obsolete=остарял
outmoded=остарял
passé=минало
unfashionable=немодерен
dated=датиран
hackneyed=изтъркан
trite=банален
banal=банален
commonplace=обикновен
mundane=ежедневен
everyday=ежедневен
routine=рутинен
habitual=привичен
customary=обичаен
usual=обичаен
typical=типичен
conventional=конвенционален
traditional=традиционен
orthodox=православен
established=установен
accepted=приет
recognized=признат
acknowledged=признат
admitted=признат
confessed=признат
declared=деклариран
announced=обявен
proclaimed=провъзгласен
affirmed=потвърден
asserted=твърден
alleged=предполагаем
claimed=твърден
purported=предполагаем
reputed=смятан
supposed=предполагаем
presumed=предполагаем
assumed=предполагаем
hypothetical=хипотетичен
speculative=спекулативен
conjectural=предполагаем
putative=смятан
nominal=номинален
titular=титулярен
so-called=тъй наречен
self-styled=самопровъзгласен
would-be=бъдещ
aspiring=стремящ се
hopeful=обнадежден
optimistic=оптимистичен
confident=уверен
positive=позитивен
assured=сигурен
convinced=убеден
persuaded=убеден
satisfied=удовлетворен
content=доволен
pleased=доволен
delighted=възхитен
elated=възвишен
enthusiastic=ентусиазиран
restless=безпокоен
uneasy=притеснен
restive=бунтовен
rebellious=бунтовен
defiant=предизвикателен
hostile=враждебен
antagonistic=антагонистичен
adverse=вреден
contrary=противоположен
opposite=противоположен
reverse=обратен
inverse=обратен
converse=обратен
polar=полярен
antithetical=антитетичен
contradictory=противоречив
inconsistent=непоследователен
incompatible=несъвместим
incongruous=нехармоничен
discrepant=различен
divergent=разминаващ се
dissimilar=несходен
unlike=несходен
diverse=разнообразен
varied=разнообразен
assorted=асортимент
mixed=смесен
miscellaneous=разнообразен
heterogeneous=хетерогенен
disparate=различен
unalike=несходен
other=друг
another=друг
alternative=алтернативен
substitute=заместващ
replacement=заместване
    """
    
    for line in adj.strip().split('\n'):
        if '=' in line:
            en, bg = line.split('=', 1)
            t[en.strip()] = bg.strip()
    
    return t


def translate_word(word, translations):
    """Translate a single word to Bulgarian."""
    # Direct lookup
    if word in translations:
        return translations[word]
    
    # Try lowercase
    lower = word.lower()
    if lower in translations:
        return translations[lower]
    
    # Try title case
    title = word.title()
    if title in translations:
        return translations[title]
    
    # Try removing "to " prefix for verbs
    if word.startswith("to "):
        verb = word[3:]
        if verb in translations:
            return translations[verb]
        if verb.lower() in translations:
            return translations[verb.lower()]
    
    # Try singular form if plural
    if word.endswith("s") and len(word) > 1:
        singular = word[:-1]
        if singular in translations:
            return translations[singular]
        if singular.lower() in translations:
            return translations[singular.lower()]
    
    # Return original if no translation found
    return word


def main():
    # Load translations
    translations = get_translations()
    
    # Load kanji data
    with open("data/export/kanji_all.json", "r", encoding="utf-8") as f:
        kanji_list = json.load(f)
    
    # Track statistics
    total_meanings = 0
    translated_count = 0
    missing = set()
    
    # Translate each kanji
    for kanji in kanji_list:
        meanings = kanji.get("meanings", [])
        total_meanings += len(meanings)
        
        bg_meanings = []
        for meaning in meanings:
            bg = translate_word(meaning, translations)
            if bg != meaning:
                translated_count += 1
            else:
                missing.add(meaning)
            bg_meanings.append(bg)
        
        # Add translations to the kanji object
        kanji["translations"] = {
            "bg": {
                "meanings": bg_meanings
            }
        }
    
    # Save translated kanji
    with open("data/export/kanji_bg.json", "w", encoding="utf-8") as f:
        json.dump(kanji_list, f, ensure_ascii=False, indent=2)
    
    # Print stats
    print(f"Total kanji: {len(kanji_list)}")
    print(f"Total meanings: {total_meanings}")
    print(f"Translated: {translated_count}")
    print(f"Missing: {len(missing)}")
    print(f"Coverage: {translated_count/total_meanings*100:.1f}%")
    
    if missing:
        print("\nMissing translations (first 50, excluding numbers/special):")
        # Filter out obvious non-translatables
        filtered = [m for m in missing if not m.startswith(('%', '-', '.', '(', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9')) and len(m) > 1]
        for m in sorted(filtered)[:50]:
            print(f"  - {m}")


if __name__ == "__main__":
    main()
