defmodule Medoru.Content.KanjiBulkFix do
  @moduledoc """
  Bulk-fix kanji with string-format strokes, missing strokes, or missing readings.

  Requires these files (generated by bin/generate_kanji_fixes.py):
  - priv/repo/seeds/bulk_stroke_fixes.json
  - priv/repo/seeds/bulk_reading_fixes.json

  Run `Medoru.Content.KanjiBulkFix.apply()` in a remote console.
  """

  alias Medoru.Repo
  alias Medoru.Content.{Kanji, KanjiReading}
  import Ecto.Query

  require Logger

  @stroke_fixes_file "priv/repo/seeds/bulk_stroke_fixes.json"
  @reading_fixes_file "priv/repo/seeds/bulk_reading_fixes.json"

  def apply do
    apply_stroke_fixes()
    apply_reading_fixes()
  end

  def apply_stroke_fixes do
    Logger.info("Loading stroke fixes...")

    fixes =
      case File.read(@stroke_fixes_file) do
        {:ok, contents} -> Jason.decode!(contents)
        {:error, _} -> %{}
      end

    if fixes == %{} do
      Logger.warning("No stroke fixes found. Run bin/generate_kanji_fixes.py first.")
      :ok
    else
      Logger.info("Loaded #{map_size(fixes)} stroke fixes")

      # Fix 1: String-format strokes -> convert to maps, replace with KanjiVG if available
      string_stroke_kanji =
        Repo.all(Kanji)
        |> Enum.filter(fn k ->
          strokes = get_in(k.stroke_data, ["strokes"])
          is_list(strokes) and length(strokes) > 0 and is_binary(hd(strokes))
        end)

      Logger.info("Found #{length(string_stroke_kanji)} kanji with string strokes")

      {fixed_with_kanjivg, fixed_fallback} =
        Enum.reduce(string_stroke_kanji, {0, 0}, fn kanji, {kv_count, fb_count} ->
          case Map.fetch(fixes, kanji.character) do
            {:ok, fix_data} ->
              current = kanji.stroke_data || %{}

              new_stroke_data =
                current
                |> Map.merge(fix_data)
                |> Map.put_new("bounds", %{"width" => 109, "height" => 109, "viewBox" => "0 0 109 109"})

              kanji
              |> Ecto.Changeset.change(stroke_data: new_stroke_data)
              |> Repo.update!()

              {kv_count + 1, fb_count}

            :error ->
              # No KanjiVG - convert strings to maps with "unknown"
              strokes = kanji.stroke_data["strokes"] || []

              new_strokes =
                strokes
                |> Enum.with_index(1)
                |> Enum.map(fn {path, idx} ->
                  %{
                    "path" => path,
                    "order" => idx,
                    "type" => "unknown",
                    "direction" => "unknown"
                  }
                end)

              current = kanji.stroke_data || %{}
              new_stroke_data = Map.put(current, "strokes", new_strokes)

              kanji
              |> Ecto.Changeset.change(stroke_data: new_stroke_data)
              |> Repo.update!()

              {kv_count, fb_count + 1}
          end
        end)

      Logger.info(
        "Fixed #{fixed_with_kanjivg} string strokes with KanjiVG, #{fixed_fallback} with fallback"
      )

      # Fix 2: "unknown" map strokes -> replace with KanjiVG if available
      unknown_stroke_kanji =
        Repo.all(Kanji)
        |> Enum.filter(fn k ->
          strokes = get_in(k.stroke_data, ["strokes"])

          is_list(strokes) and is_map(hd(strokes)) and
            (hd(strokes)["type"] == "unknown" or hd(strokes)["direction"] == "unknown")
        end)
        |> Enum.filter(fn k -> Map.has_key?(fixes, k.character) end)

      Logger.info("Found #{length(unknown_stroke_kanji)} kanji with unknown strokes to replace")

      replaced_count =
        Enum.reduce(unknown_stroke_kanji, 0, fn kanji, count ->
          fix_data = fixes[kanji.character]
          current = kanji.stroke_data || %{}

          new_stroke_data =
            current
            |> Map.merge(fix_data)
            |> Map.put_new("bounds", %{"width" => 109, "height" => 109, "viewBox" => "0 0 109 109"})

          kanji
          |> Ecto.Changeset.change(stroke_data: new_stroke_data)
          |> Repo.update!()

          count + 1
        end)

      Logger.info("Replaced #{replaced_count} unknown strokes with KanjiVG")

      # Fix 3: No stroke data -> add KanjiVG if available
      no_stroke_kanji =
        Repo.all(Kanji)
        |> Enum.filter(fn k ->
          is_nil(k.stroke_data) or k.stroke_data == %{} or
            is_nil(k.stroke_data["strokes"]) or k.stroke_data["strokes"] == []
        end)
        |> Enum.filter(fn k -> Map.has_key?(fixes, k.character) end)

      Logger.info("Found #{length(no_stroke_kanji)} kanji with no strokes to add")

      added_count =
        Enum.reduce(no_stroke_kanji, 0, fn kanji, count ->
          fix_data = fixes[kanji.character]

          new_stroke_data =
            fix_data
            |> Map.put_new("bounds", %{"width" => 109, "height" => 109, "viewBox" => "0 0 109 109"})

          kanji
          |> Ecto.Changeset.change(stroke_data: new_stroke_data)
          |> Repo.update!()

          count + 1
        end)

      Logger.info("Added stroke data to #{added_count} kanji")

      total = fixed_with_kanjivg + fixed_fallback + replaced_count + added_count
      {:ok, total}
    end
  end

  def apply_reading_fixes do
    Logger.info("Loading reading fixes...")

    fixes =
      case File.read(@reading_fixes_file) do
        {:ok, contents} -> Jason.decode!(contents)
        {:error, _} -> %{}
      end

    if fixes == %{} do
      Logger.warning("No reading fixes found. Run bin/generate_kanji_fixes.py first.")
      :ok
    else
      Logger.info("Loaded #{map_size(fixes)} reading sets")

      # Find kanji with stroke data but zero readings
      kanji_without_readings =
        from(k in Kanji,
          left_join: r in assoc(k, :kanji_readings),
          where: not is_nil(k.stroke_data) and k.stroke_data != ^%{},
          group_by: k.id,
          having: count(r.id) == 0,
          select: k
        )
        |> Repo.all()

      Logger.info("Found #{length(kanji_without_readings)} kanji without readings")

      inserted_count =
        Enum.reduce(kanji_without_readings, 0, fn kanji, count ->
          case Map.fetch(fixes, kanji.character) do
            {:ok, readings} when is_list(readings) and readings != [] ->
              inserted =
                Enum.reduce(readings, 0, fn reading_data, inner_count ->
                  attrs = %{
                    kanji_id: kanji.id,
                    reading_type: String.to_atom(reading_data["type"]),
                    reading: reading_data["reading"],
                    romaji: reading_data["romaji"] || ""
                  }

                  case %KanjiReading{}
                       |> KanjiReading.changeset(attrs)
                       |> Repo.insert() do
                    {:ok, _} -> inner_count + 1
                    {:error, _} -> inner_count
                  end
                end)

              count + inserted

            _ ->
              count
          end
        end)

      Logger.info("Inserted #{inserted_count} readings")
      {:ok, inserted_count}
    end
  end
end
