defmodule MedoruWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :medoru

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # Session cookie lasts 60 days so PWA users stay logged in
  @session_options [
    store: :cookie,
    key: "_medoru_key",
    signing_salt: "zfg0u6c5",
    same_site: "Lax",
    max_age: 60 * 24 * 60 * 60
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Prevent caching of service-worker.js so browsers always check for updates
  plug MedoruWeb.Plugs.NoCacheServiceWorker

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :medoru,
    gzip: not code_reloading?,
    only: MedoruWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Serve uploaded files from external directory (configured via UPLOADS_DIR env var)
  plug Plug.Static,
    at: "/uploads",
    from: System.get_env("UPLOADS_DIR") || "/var/opt/medoru/uploads",
    gzip: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :medoru
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: 210_000_000

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug MedoruWeb.Plugs.CORS
  plug MedoruWeb.Router
end
